nohup: ignoring input
[2025-03-13 17:08:28 +0100] [501912] [INFO] Starting gunicorn 20.1.0
[2025-03-13 17:08:28 +0100] [501912] [INFO] Listening at: http://0.0.0.0:8888 (501912)
[2025-03-13 17:08:28 +0100] [501912] [INFO] Using worker: sync
[2025-03-13 17:08:28 +0100] [501913] [INFO] Booting worker with pid: 501913
[2025-03-13 17:08:28 +0100] [501913] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/user1/app/cyber_dashboard/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/user1/app/cyber_dashboard/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/user1/app/cyber_dashboard/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/user1/app/cyber_dashboard/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/user1/app/cyber_dashboard/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user1/app/cyber_dashboard/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user1/app/cyber_dashboard/venv/lib/python3.12/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2025-03-13 17:08:28 +0100] [501913] [INFO] Worker exiting (pid: 501913)
[2025-03-13 17:08:28 +0100] [501912] [INFO] Shutting down: Master
[2025-03-13 17:08:28 +0100] [501912] [INFO] Reason: Worker failed to boot.
